### ISSUE TITLE
Its very Good！ But does it support cache to disk?

### ISSUE THREAD

**Issue by z234009184** [gskinner/image_fade#5]

**Comment by clragon** [comment]
caching to disk isn't the job of this widget, use a [NetworkImage](https://api.flutter.dev/flutter/painting/NetworkImage-class.html) as provider to get caching.

**Comment by gskinner** [comment]
I know this is super late, but as @clragon suggested, caching is outside the purview of this widget. NetworkImage does some caching, and you can also use `CachedNetworkImageProvider`.
